name: build backend

on:
  push:
    paths:
      - 'backend/**'
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11

      - name: Login to GitHub Package Registry
        uses: docker/login-action@v1.9.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          TAG="ghcr.io/${{ github.repository_owner }}/iac-workshop-backend:latest"
          echo "Pushing to tag $TAG"
          mvn clean package -Djib.to.image=$TAG
        working-directory: backend
