name: build frontend

on:
  push:
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend.yml'
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: npm install & build
        run: |
          npm ci
          REACT_APP_BACKEND_URL=will-be-replaced-by-terraform npm run build --if-present
          (cd build && zip -r ../release.zip ./*)
        working-directory: frontend

      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: Frontend release ${{ github.sha }}
          tag_name: frontend-${{ github.job }}-${{ github.sha }}
          body: Frontend release
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Upload frontend artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: frontend/release.zip
          asset_name: iac-workshop-frontend.zip
          asset_content_type: application/zip